name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # Set up PHP environment
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer

    # Checkout project code
    - name: Checkout code
      uses: actions/checkout@v4

    # Clear Composer cache
    - name: Clear Composer Cache
      run: composer clear-cache

    # Copy .env file if it doesn't exist
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # Install Composer dependencies
    - name: Install Dependencies
      run: |
        composer install --no-scripts --prefer-dist
        composer run-script post-install-cmd

    # Generate application key
    - name: Generate Application Key
      run: php artisan key:generate

    # Set correct permissions for storage and cache directories
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Create SQLite database file for testing
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    # Run database migrations
    - name: Run Migrations
      run: php artisan migrate --force
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite

    # Run Laravel tests
    - name: Run Tests
      run: php artisan test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
